// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfhqyxcgurlpcvbzdoeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmaHF5eGNndXJscGN2Ynpkb2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MTM0NzUsImV4cCI6MjA1MTk4OTQ3NX0.eFtBoFBtPwabeYh2XvV2f16mPuBk4bKKpne7I_25a2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);